### ISSUE TITLE
Missing Copright information

### ISSUE THREAD

**Issue by MarcusBiel** [fzoli/Sudoku#1]
Hi, what is the copyright of your code? Is it okay to use it?

**Comment by fzoli** [comment]
Hi.
It is OK. :)

Marcus Biel <notifications@github.com> ezt írta (időpont: 2019. ápr. 14.,
Vas 19:45):

**Comment by MarcusBiel** [comment]
Hi. Please get in touch with me, as I would like to share some more details with you. I don't want to leave my email here in public, but you can easily contact me over my website, or over Twitter.
'
